routing settings
dmytro-honch/solar-system-observer pull request #2
Opened 2023-06-16 18:13 UTC by 47codemonkey

Пока только пути прописал. Компоненты сейчас буду создавать в этой же ветке

2023-06-16 18:29 UTC, 47codemonkey commented
Порезолвил твои конфликты

2023-06-17 10:35 UTC, dmytro-honch requested changes

2023-06-17 10:35 UTC, dmytro-honch commented on src/features/AboutProject/index.tsx
> +export default AboutProject
You have to apply prettier changes onSave action in VS code. So, here should be semicolon.

2023-06-17 10:35 UTC, dmytro-honch commented on src/features/AboutProject/index.tsx
> +import { PLANET_OBSERVER_PATH } from '../Router/pathes.ts';
Please, use absolute path in imports 'src/features/Router...'

2023-06-17 10:35 UTC, dmytro-honch commented on src/features/AboutProject/index.tsx
> +export default AboutProject
This changes for whole PR.

2023-06-17 10:35 UTC, dmytro-honch commented on src/features/AboutProject/index.tsx
> +import { PLANET_OBSERVER_PATH } from '../Router/pathes.ts';
This changes for whole PR.

2023-06-17 10:35 UTC, dmytro-honch commented on src/features/Router/index.tsx
> +import { MENU_PATH, PLANET_OBSERVER_PATH, FALLBACK_404_ROUTE, CONTACT_US_PATH, ABOUT_US_PATH, SOLAR_SYSTEM_PATH } from './pathes.ts';
don't use file extension in paths for ts/tsx/js/jsx files

2023-06-17 10:35 UTC, dmytro-honch commented on src/features/Menu/index.tsx
> +        <a href={SAY_THANKS_PATH}>Say thanks</a>
well done :)

2023-06-17 19:37 UTC, 47codemonkey commented
Hey there. Kindly check my last commit "some minor changes' Thx in advance

2023-06-17 19:57 UTC, dmytro-honch requested changes

2023-06-17 19:57 UTC, dmytro-honch commented on src/features/ContactUs/index.tsx
> +import { PLANET_OBSERVER_PATH } from '../Router/pathes.ts';
Please, rename filename "pathes" with "path". My typo :)

2023-06-17 19:57 UTC, dmytro-honch commented on src/features/SolarSystemObjects/index.tsx
> +import { PLANET_OBSERVER_PATH } from '../Router/pathes.ts';
use absolute path

2023-06-17 19:57 UTC, dmytro-honch commented on src/features/Menu/index.tsx
> +import { SAY_THANKS_PATH } from 'src/features/Router/pathes.ts';
delete file extensions

2023-06-17 19:57 UTC, dmytro-honch commented on src/features/ContactUs/index.tsx
> +import { PLANET_OBSERVER_PATH } from 'src/features/Router/pathes.ts';
delete file extension

2023-06-17 19:57 UTC, dmytro-honch commented on src/features/AboutProject/index.tsx
> +import { PLANET_OBSERVER_PATH } from 'src/features/Router/pathes.ts';
delete file extension

2023-06-17 20:09 UTC, dmytro-honch approved these changes

2023-06-17 20:11 UTC, merged